### ISSUE TITLE
Add scopt dependency in Jar or publis assembly Jar

### ISSUE THREAD

**Issue by gquintana** [CoxAutomotiveDataSolutions/spark-distcp#7]
The Jar published in Maven Central doesn't contain required scopt classes
```
Exception in thread "main" java.lang.NoClassDefFoundError: scopt/OptionParser
        at com.coxautodata.SparkDistCP$.main(SparkDistCP.scala:49)
        at com.coxautodata.SparkDistCP.main(SparkDistCP.scala)
```

A fat jar (uberjar) containing everything needed would make running spark-distcp easier

The scopt dependency is present in the assembly Jar which is a fatjar, but this Jar is not published to Maven Central.

**Comment by jamesfielder** [comment]
Had a first go at this in PR #13

**Comment by jamesfielder** [comment]
Going to try publishing an assembly jar to maven now, then will look at #10 over the next few days (and potentially publish a new version for that after).

**Comment by jamesfielder** [comment]
There is now an assembly jar available from maven: https://search.maven.org/artifact/com.coxautodata/spark-distcp_2.12/0.2.5/assembly 

I've included scopt in the jar, but shaded it (just as a slight hedge against classpath issues). Let me know if this is all good for you!
